# Generated by Django 4.1 on 2023-06-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='desc',
            field=models.CharField(default='无', max_length=100, verbose_name='描述'),
        ),
    ]
