# Generated by Django 4.1 on 2023-06-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='pubData',
            new_name='pubDate',
        ),
    ]
