# Generated by Django 4.1 on 2023-06-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_rename_pubdata_diary_pubdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': '日记'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='desc',
            field=models.CharField(default=' ', max_length=100, verbose_name='描述'),
        ),
    ]
