# Generated by Django 4.1 on 2023-06-24 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_options_alter_diary_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='desc',
            field=models.CharField(blank=True, default=' ', max_length=100, verbose_name='描述'),
        ),
    ]
