# Generated by Django 3.1.6 on 2022-02-07 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未分类', max_length=50)),
            ],
            options={
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Micro_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateField(unique=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('html_generate_date', models.DateTimeField(blank=True, null=True)),
                ('markdown_text', models.TextField()),
                ('html_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '微博',
                'ordering': ['-pubdate'],
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('html_generate_date', models.DateTimeField(blank=True, null=True)),
                ('markdown_text', models.TextField(blank=True, null=True)),
                ('html_text', models.TextField(blank=True, null=True)),
                ('text_type', models.CharField(default='markdown', max_length=20)),
            ],
            options={
                'verbose_name_plural': '特殊页面',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(default='Dongliu', max_length=50)),
                ('visits', models.BigIntegerField(default=0)),
                ('abstract', models.TextField(null=True)),
                ('markdown_text', models.TextField(default='# 无内容')),
                ('html_text', models.TextField(blank=True, null=True)),
                ('pubdate', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('html_generate_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.categories')),
                ('tags', models.ManyToManyField(to='article.Tags')),
            ],
            options={
                'verbose_name_plural': '博客',
                'ordering': ['-pubdate'],
            },
        ),
    ]
