# Generated by Django 3.2.5 on 2022-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('pubdate', models.DateTimeField()),
                ('modify_date', models.DateTimeField()),
                ('categories', models.CharField(max_length=50, null=True)),
                ('tags', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
