# Generated by Django 3.2.5 on 2022-01-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_weibo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='weibo',
            new_name='micro_blog',
        ),
    ]
