# Generated by Django 3.2.5 on 2022-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20220208_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='markdown_text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='micro_blog',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
