# Generated by Django 3.2.5 on 2022-01-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_weibo_micro_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
