# Generated by Django 3.2.5 on 2022-02-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20220208_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='html_generate_date',
        ),
        migrations.RemoveField(
            model_name='micro_blog',
            name='html_generate_date',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='html_generate_date',
        ),
        migrations.AddField(
            model_name='blog',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='micro_blog',
            name='updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pages',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
