# Generated by Django 3.2.5 on 2022-01-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
