# Generated by Django 3.2.5 on 2022-01-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_article_visits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='blog',
        ),
    ]
