# Generated by Django 3.2.5 on 2022-07-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20220707_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='micro_blog',
            name='description',
            field=models.CharField(default='blank', max_length=20),
        ),
    ]
