# Generated by Django 3.2.5 on 2022-01-31 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_rename_article_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categories',
            new_name='category',
        ),
    ]
