# Generated by Django 3.2.5 on 2022-07-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_alter_micro_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='private',
        ),
        migrations.RemoveField(
            model_name='micro_blog',
            name='private',
        ),
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='micro_blog',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
