# Generated by Django 3.2.5 on 2022-02-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20220201_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': '特殊页面',
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['pubdate'], 'verbose_name_plural': '博客'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['name'], 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='micro_blog',
            options={'ordering': ['pubdate'], 'verbose_name_plural': '微博'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['name'], 'verbose_name_plural': '标签'},
        ),
    ]
