# Generated by Django 3.2.5 on 2022-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20220201_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='html_generate_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='markdown_text',
            field=models.TextField(),
        ),
    ]
