# Generated by Django 3.2.5 on 2022-02-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20220201_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_generate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
