# Generated by Django 3.2.5 on 2022-02-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20220202_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
