# Generated by Django 3.2.5 on 2022-02-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_alter_micro_blog_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='pubdate',
            field=models.DateField(),
        ),
    ]
