# Generated by Django 3.2.5 on 2022-02-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_alter_micro_blog_pubdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
