# Generated by Django 3.2.5 on 2022-02-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_alter_micro_blog_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='micro_blog',
            name='html_generate_date',
            field=models.DateTimeField(null=True),
        ),
    ]
