# Generated by Django 3.2.5 on 2022-02-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20220202_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='markdown_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(verbose_name=models.DateTimeField()),
        ),
    ]
