# Generated by Django 3.2.5 on 2022-02-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20220202_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
