# Generated by Django 3.2.5 on 2022-02-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_remove_micro_blog_modify_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='html_generate_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='html_text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='markdown_text',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='visits',
        ),
        migrations.AddField(
            model_name='micro_blog',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
