# Generated by Django 3.2.5 on 2022-02-02 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0028_auto_20220202_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Dongliu', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.categories'),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_generate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='html_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='markdown_text',
            field=models.TextField(default='# 无内容'),
        ),
        migrations.AddField(
            model_name='blog',
            name='modify_date',
            field=models.DateTimeField(default=models.DateTimeField()),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='article.Tags'),
        ),
        migrations.AddField(
            model_name='blog',
            name='visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
