# Generated by Django 3.2.5 on 2022-02-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20220202_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='markdown_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
