# Generated by Django 3.2.5 on 2022-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_alter_pages_markdown_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='micro_blog',
            name='pubdate',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
