# Generated by Django 3.2.5 on 2022-10-15 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='书名')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(verbose_name='内容')),
                ('note_time', models.DateTimeField(verbose_name='添加时间')),
                ('note_location', models.CharField(max_length=30, verbose_name='添加位置')),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.books', verbose_name='书名')),
            ],
            options={
                'verbose_name': '标注',
                'verbose_name_plural': '标注',
            },
        ),
    ]
