# Generated by Django 3.2.5 on 2022-10-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='note_nums',
            field=models.IntegerField(default=0, verbose_name='笔记条数'),
            preserve_default=False,
        ),
    ]
