# Generated by Django 3.2.5 on 2022-10-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_books_note_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_date', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('context', models.TextField(verbose_name='剪切板内容')),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_time',
            field=models.CharField(max_length=50, verbose_name='添加时间'),
        ),
    ]
