# Generated by Django 3.2.5 on 2022-10-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_auto_20221015_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindnotes',
            old_name='context',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='context',
            new_name='content',
        ),
    ]
