# Generated by Django 3.2.5 on 2022-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0005_remove_books_note_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='书名'),
        ),
    ]
