# Generated by Django 4.1 on 2023-01-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0006_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='书名'),
        ),
    ]
