# Generated by Django 4.1 on 2023-04-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0007_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=100, verbose_name='作者'),
        ),
    ]
