# Generated by Django 3.2.5 on 2022-02-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_rename_content_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
