# Generated by Django 3.2.5 on 2022-02-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_auto_20220208_1025'),
    ]

    operations = [
    ]
