# Generated by Django 3.2.5 on 2022-02-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0007_auto_20220208_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='image/'),
        ),
    ]
