# Generated by Django 3.2.5 on 2022-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0008_auto_20220208_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['pubdate'], 'verbose_name_plural': '图片'},
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
